name: Setup asdf-vm with cache
description: |
  Will download asdf-vm with cache.
  Initialize JAVA_HOME if java is specified in .tool-version

inputs: {}

outputs:
  cache-hit:
    description: A boolean value to indicate the dependencies were loaded from an exact cache hit.
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Install asdf-vm
      uses: asdf-vm/actions/setup@v3.0.0
      
    # Some tools fork processes in odd working directories. Adding dependencies to global helps.
    - shell: bash
      run: cp -f .tool-versions ~/.tool-versions 

    - name: Cache asdf tooling
      uses: actions/cache@v3
      id: cache
      with:
        key: asdf-${{ runner.os }}-${{ hashFiles('.tool-versions') }}
        path: |
          ${{ env.ASDF_DIR }}/installs
          ${{ env.ASDF_DIR }}/plugins

    - name: Install asdf-vm tools
      uses: asdf-vm/actions/install@v3.0.0
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        before_install: |
          if [ -f "${ASDF_DIR}/plugins/nodejs/bin/import-release-team-keyring" ]; then
            ${ASDF_DIR}/plugins/nodejs/bin/import-release-team-keyring
          fi

    - name: Reshim asdf-vm tools
      if: steps.cache.outputs.cache-hit == 'true'
      shell: bash
      run: asdf reshim

    - name: Switch to the asdf-provided version of java
      shell: bash
      run: |
        grep java .tool-versions && echo "JAVA_HOME=$(dirname "$(dirname "$(realpath "$(asdf which java)")")")" >> $GITHUB_ENV || true
