name: Setup asdf-vm with cache
description: |
  Will download asdf-vm with cache.
  Initialize JAVA_HOME if java is specified in .tool-version

inputs:
  working-directory:
    description: Path where the root project is located.
    required: false
    default: "."

outputs:
  cache-hit:
    description: A boolean value to indicate the dependencies were loaded from an exact cache hit.
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Install asdf-vm
      uses: asdf-vm/actions/setup@v4.0.0
      with:
        asdf_branch: v0.15.0

    # Some tools fork processes in odd working directories. Adding dependencies to global helps.
    - shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        cp -f .tool-versions ~/.tool-versions
        if [ "${{ inputs.working-directory }}" != "." ] && [ "${{ inputs.working-directory }}" != "" ]; then
          cp -f .tool-versions ${{ github.workspace }}/.tool-versions
        fi

    - name: Cache asdf tooling
      uses: actions/cache@v4
      id: cache
      with:
        key: asdf-${{ runner.os }}-${{ hashFiles('.tool-versions') }}
        path: |
          ${{ env.ASDF_DIR }}/installs
          ${{ env.ASDF_DIR }}/plugins

    - name: Install asdf-vm tools
      uses: asdf-vm/actions/install@v4.0.0
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        asdf_branch: v0.15.0
        before_install: |
          if [ -f "${ASDF_DIR}/plugins/nodejs/bin/import-release-team-keyring" ]; then
            ${ASDF_DIR}/plugins/nodejs/bin/import-release-team-keyring
          fi

    - name: Reshim asdf-vm tools
      if: steps.cache.outputs.cache-hit == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: asdf reshim

    - name: Switch to the asdf-provided version of java
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        grep java .tool-versions && echo "JAVA_HOME=$(dirname "$(dirname "$(realpath "$(asdf which java)")")")" >> $GITHUB_ENV || true
